### ISSUE TITLE
edit the expression to be substituted?

### ISSUE THREAD

**Issue by abtxu** [protesilaos/substitute#10]
When the following pop up when using substitute pacakage, 
Substitute x from the point to the end of the buffer with: 
I can not go back to change x.
Would be very nice to to have that function. Thanks.

**Comment by protesilaos** [comment]
Hello @abtxu!  I am not sure I follow you.  Maybe you can show me an example?

**Comment by abtxu** [comment]
Hi Prot,

Sorry I did not make it clear enough. 

Here is an example:

When I want to substitute "substitute" with "replace" across the buffer, I run the command and emacs will prompt:

Substite 'substitute' across the buffer with: 

Then I realize I only want to replace part of the word "substitute", say "sub", but I can not go back to edit it. I can only C-g to quit and then select the part on "sub" and start over again.

Forget it if you think this is too trivial.

**Comment by protesilaos** [comment]
Oh, I see.  This is not possible.  Once a value has been confirmed, we cannot go back and edit it.  You have to start from the beginning.  This is how Emacs handles all prompts.

**Comment by abtxu** [comment]
Thank you Prot. No problem, and you can close the issue if you like.

**Comment by protesilaos** [comment]
Thank you!
