### ISSUE TITLE
Add barf-if-buffer-read-only

### ISSUE THREAD

**Issue by ersi-dnd** [protesilaos/substitute#6]
Congrats for a nice package. Just one improvement suggestion. The commands take their sweet time to do their thing when in read-only buffers, but fail without error message. Therefore:
```
(defun substitute--prompt (target scope)
  "Return appropriate prompt based on `substitute-highlight'.
Pass to it the TARGET and SCOPE arguments."
  (barf-if-buffer-read-only)
  (funcall
   (if substitute-highlight
       'substitute--prompt-with-highlight
     'substitute--prompt-without-highlight)
   target
   scope))
```

**Comment by ersi-dnd** [comment]
This would be my first ever pull request or patch. I don't have the time to learn to do them now. Just copy the idea. You have my permission right here. (It's not like it's any novel idea anyway.)

And congrats again for the nice package. I'm a happy diligent user.

**Comment by protesilaos** [comment]
Done.  Thank you!
