### ISSUE TITLE
Scope of point

### ISSUE THREAD

**Issue by artelse** [protesilaos/substitute#8]
When I have a symbol like `substitute-target-below-point` and the point at `target` the search selects the whole symbol and not just `target`. Is there a way to limit how substitute handles this case or does it make it too cumbersome to use with an extra option of sorts? Thanks for all your packages btw!

**Comment by protesilaos** [comment]
> From: artelse ***@***.***>
> Date: Sat,  1 Jul 2023 15:36:08 -0700
>
> When I have a symbol like `substitute-target-below-point` and the
> point at `target` the search selects the whole symbol and not just
> `target`. Is there a way to limit how substitute handles this case or
> does it make it too cumbersome to use with an extra option of sorts?

You can target a specific string by marking the region to include it.
Otherwise, the target will always be the symbol at point.

> Thanks for all your packages btw!

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com
