### ISSUE TITLE
Typo in defaliases

### ISSUE THREAD

**Issue by ersi-dnd** [protesilaos/substitute#9]
In substitute.el there is `(defalias 'substitute-target-to-end-of-buffer 'substitute-target-below-point)` and `(defalias 'substitute-target-to-beginning-of-buffer 'substitute-target-below-point)` 

Surely the latter should be `(defalias 'substitute-target-to-beginning-of-buffer 'substitute-target-above-point)` ?

**Comment by protesilaos** [comment]
Thank you @ersi-dnd!  I just pushed the change.
